export const ActionTypes = {
  IMAGES_FETCHED: 'IMAGES_FETCHED',
  FETCH_SERVER_IMAGES: 'FETCH_SERVER_IMAGES',
  IMAGES_SAVED_COMPLETED: 'IMAGES_SAVED_COMPLETED',
  IMAGES_SAVED_COMPLETE: 'IMAGES_SAVED_COMPLETE',
  IMAGE_SAVE: 'IMAGE_SAVE',
  IMAGE_SAVED: 'IMAGE_SAVED',
};
